### PR TITLE
[489208] fixed problem of refactoring anon inner classes

### PR DESCRIPTION
**Pull request by cdietrich**
[489208] fixed problem of refactoring anon inner classes

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=489208

**Comment by cdietrich** [comment]
@JanKoehnlein @szarnekow what do you think.

please note: this is affected by https://github.com/eclipse/xtext-xtend/issues/166 as well

**Comment by cdietrich** [comment]
well that destroys the validation of anon classes.

**Comment by cdietrich** [comment]
well i think i have found a solution

**Comment by cdietrich** [comment]
please review

**Pull request merged**
