### PR TITLE
[502897] Streamlined plugin metadata

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms karsten.thoms@itemis.de

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=502897

**Comment by dhuebner** [comment]
@kthoms Xtend is not an eclipse project, hence we can not use Eclipse Xtend as Vendor name. If you look into the commit history we changed "Eclipse Xtend" to "Eclipse Xtext"  after merging Xtend into the Xtext repository. I'm afraid we need to revert this PR.

**Comment by cdietrich** [comment]
so eclipse xtext should be used everywhere?

**Comment by dhuebner** [comment]
@cdietrich Yes, please change all the Vendor entries to "Eclipse Xtext"

**Comment by kthoms** [comment]
OK, can do that.

**Comment by kthoms** [comment]
@dhuebner Find the requested change in #86

**Pull request merged**
