### PR TITLE
Fix broken aa class loading

### LINKED ISSUE #282: [AA] ProcessorInstanceForJvmTypeProvider uses wrong classloader to load AA Processors
https://services.typefox.io/open-source/jenkins/job/xtext-core/job/milestone_2.13.0.RC1/4/console

:org.eclipse.xtext.tests:generateTestXtextERROR:Type mismatch: cannot convert from boolean to Function<String, String> (file:/var/jenkins_home/workspace/t-core_milestone_2.13.0.RC1-5N4QLOLQECB5ZLOIEXO3EWYF7FRVEM25USVJP3F3NVYI7YAJSXWA/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/TracingSugarTest.xtend line : 242 column : 19)
 FAILED

### PR DESCRIPTION
**Pull request by cdietrich**
Fixes #282

### CODE REVIEW

**Comment by cdietrich** [comment]
Please review

**Comment by szarnekow** [comment]
:+1:

**Comment by cdietrich** [comment]
@svenefftinge what do you think?

**Comment by svenefftinge** [comment]
Thanks, for taking action. This might break any AAs where people downcast to the implementations to get access to any non-exposed things (e.g. EMF objects). But I guess we have to live with that.

**Comment by cdietrich** [comment]
@svenefftinge downcasting is not working, even without that change. at least not in eclipse

**Pull request merged**
