### PR TITLE
preserve parameter names during compilation with tycho

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by kthoms** [comment]
I guess this solves the "arg0" problem?
https://www.concretepage.com/java/jdk-8/java-8-reflection-access-to-parameter-names-of-method-and-constructor-with-maven-gradle-and-eclipse-using-parameters-compiler-argument#compiler-argument

**Comment by cdietrich** [comment]
yes this is what we found last week during the WS. this is a downport from arnes branch and  complements the changes i did already for the gradle builds last week

**Comment by kthoms** [comment]
Could you maybe add a hint in the commit message body, e.g. to the link above or something similar?

**Comment by cdietrich** [comment]
the page https://help.eclipse.org/2019-06/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm is not deep linkable

**Pull request merged**
