### PR TITLE
Xtext Bootstrap 2.15

### PR DESCRIPTION
**Pull request by kthoms**

### CODE REVIEW

**Comment by cdietrich** [comment]
Miss changes for maven and tycho

**Comment by kthoms** [comment]
Could you be a bit more specific?

**Comment by kthoms** [comment]
<xtend-maven-plugin-version>2.14 in Tycho parent found

**Comment by cdietrich** [comment]
Tycho should bootstrap against 2.15 too and needs to remove the workaround

**Comment by kthoms** [comment]
Like that?

**Comment by cdietrich** [comment]
Yes

**Comment by cdietrich** [comment]
@kthoms  can be merged now

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-xtend/job/kth_issue1272_2/

**Pull request merged**
