### PR TITLE
Fixed broken XtendCompilerAntTaskTest. Added missing test resources. …

### LINKED ISSUE #126: Fix XtendCompilerAntTaskTest
Failing after move from xtend.core tests to xtend.ide.tests:
* org.eclipse.xtend.ide.tests.compiler.batch.XtendCompilerAntTaskTest.testSrcdirAsAttr
* org.eclipse.xtend.ide.tests.compiler.batch.XtendCompilerAntTaskTest.testSrcdirAsNestedPath

### PR DESCRIPTION
**Pull request by cdietrich**
Fixed broken XtendCompilerAntTaskTest. Added missing test resources. Fixes #126

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by kthoms** [comment]
Is it intended that the folder "test data" contains a whitespace? If not I'd prefer to rename the folder.

**Comment by cdietrich** [comment]
Yes of course . That's what is actually tested

**Comment by cdietrich** [comment]
Ps this is just a copy and paste of the stuff miso missed to copy and paste

**Comment by cdietrich** [comment]
@spoenemann should this go to master only or do we need it on maintenance as well

**Comment by spoenemann** [comment]
Please merge it to `release_2.11.0` so we'll include that test in the release build and in the following maintenance builds.

**Comment by spoenemann** [comment]
You copied the files; would it be possible to move them instead? Are they needed by other tests in xtend.core.tests?

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext-xtend/pull/135

**Pull request closed without merging**
