### PR TITLE
 [eclipse#397] Added validation, qfixes and J2X, if ternary expression is used.

### PR DESCRIPTION
**Pull request by epoell**
If a ternary expression like "a = cond? 1 : 2" is used, an issue is raised. The default setting for this issue is ignore and can be configured in "Xtend - Errors/Warnings - Code Style".
Also a quickfix is available (if marked as more than ignore), to replace this ternary expression with a normal if expression: "a = if (cond) 1 else 2".
This quickfix is applied recursively to nested usages of ternary expressions (like "a = cond? !cond? 4 : 5 : 2") . The issue however is raised only once fo that line.
Issue raise and Quickfix are covered with JUnitTests.
Java2Xtend functionality: When "Paste Java Code" is clicked and if the issue is marked as ignore (= ternary expressions are allowed), a ternary expression is inserted. If the issue is marked as info/warning/error, the ternary expression will be replaces with a normal if expression. This, too, is covered with a small JUnitTest.
However this functionality only fires, if the ternary expression is not nested.

Signed-off-by: Eva Poell <epoell@itemis.com>

### CODE REVIEW

**Comment by epoell** [comment]
Hello,
I need some help or hints on how to set the target right.

Jenkins fails to build the commit as it cannot load the target `https://ci.eclipse.org/xtext//job/xtext-eclipse/job/sz_issue397/lastStableBuild/artifact/build/p2-repository/`.
I think I need that branch's (sz_issue397) results, as Sebastian added the new grammar rules for ternary if and try with resources in the ["commit 'First shot at ternary operator in Xtend'"](https://github.com/eclipse/xtext-xtend/commit/8287ed42c3ccf93b3aeb17db669f6132fefa15d7) there, which I refer here. But maybe I misunderstood.

Thanks already!
Eva

P.S: The whole error output of jenkins:
```
[ERROR] Failed to resolve target definition /jobs/genie.xtext/xtext-xtend/branches/PR-733/workspace/releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target: Failed to load p2 metadata repository from location https://ci.eclipse.org/xtext//job/xtext-eclipse/job/sz_issue397/lastStableBuild/artifact/build/p2-repository/: No repository found at https://ci.eclipse.org/xtext//job/xtext-eclipse/job/sz_issue397/lastStableBuild/artifact/build/p2-repository. -> [Help 1]
```

**Comment by kthoms** [comment]
The job you depend on did not build successfully yet. https://ci.eclipse.org/xtext/job/xtext-eclipse/job/sz_issue397/
So it did not produce a repository so far. This needs to be fixed before.

**Comment by kthoms** [comment]
It required an upstream repository from xtext-extras, which was not available at the build time. The xtext-extras repository exists, so I retriggered the xtext-eclipse build.

**Comment by epoell** [comment]
You just started that build, right? So I only have to wait for that or should I change something?

**Comment by kthoms** [comment]
You just have to wait for a green upstream build.

**Comment by epoell** [comment]
Thanks a lot :)

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext-xtend/pull/769
thx @epoell

**Pull request closed without merging**
