### PR TITLE
[eclipse/xtext#1573] Do not share output folders mvn vs Eclipse

### PR DESCRIPTION
**Pull request by szarnekow**
[eclipse/xtext#1573] Do not share output folders between mvn and Eclipse

### CODE REVIEW

**Comment by cdietrich** [comment]
@szarnekow needs rebasing to build properly

**Comment by cdietrich** [comment]
@ArneDeutsch please reexamine

**Comment by cdietrich** [comment]
ping @ArneDeutsch

**Comment by szarnekow** [comment]
@ArneDeutsch Please review, even though I did already merge this.

**Pull request merged**
