### PR TITLE
Adding tests for dirty state type modifiers.

### PR DESCRIPTION
**Pull request by cdietrich**
see eclipse/xtext-eclipse#28
see eclipse/xtext-eclipse#30

replaces https://github.com/eclipse/xtext-xtend/pull/23

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by LorenzoBettini** [comment]
@cdietrich If I understand correctly, this PR does not only add a test but also introduces the fix? Or must the actual fix be taken directly from https://github.com/eclipse/xtext-eclipse/pull/30 ?

**Comment by LorenzoBettini** [comment]
@cdietrich I give the answer myself :) your tests succeed once I also take the commit of https://github.com/eclipse/xtext-eclipse/pull/30 (while one of the new tests fail without that). I'm running a Jenkins build for https://github.com/eclipse/xtext-eclipse/pull/30 just to make sure it does not break anything else, then I think we could merge https://github.com/eclipse/xtext-eclipse/pull/30 and then this PR, is that OK?

**Comment by cdietrich** [comment]
ok ill have a look why the ip validaiton complains

**Comment by LorenzoBettini** [comment]
The build works so I'll merge

**Pull request merged**
