### PR TITLE
eclipse/xtext-eclipse#539 Make dialog compatible with Eclipse Photon.

### PR DESCRIPTION
**Pull request by ArneDeutsch**
Implemented the dialog in a way such that it is compatible with Eclipse
Photon as well as with older Eclipse versions. Some nasty reflection is
needed to maintain backwards compatibility. Should be replaced with
Xtext based implementation in future.

Change-Id: Icecbf625da3fd2244ae507c83c0c90e481b5f38e
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-xtend/job/xtext-eclipse-539/

**Comment by cdietrich** [comment]
for tests on mac

```
if (Platform.getOS().equals(Platform.OS_MACOSX)) {
			// On Mac, the Preferences menu is under the system menu
			final IWorkbench workbench = PlatformUI.getWorkbench();
			workbench.getDisplay().asyncExec(() -> {
				IWorkbenchWindow window = workbench.getActiveWorkbenchWindow();
				if (window != null) {
					Menu appMenu = workbench.getDisplay().getSystemMenu();
					for (MenuItem item : appMenu.getItems()) {
						if (item.getText().startsWith("Preferences") || item.getText().startsWith("Einstellungen")) {
							Event event = new Event();
							event.time = (int) System.currentTimeMillis();
							event.widget = item;
							event.display = workbench.getDisplay();
							item.setSelection(true);
							item.notifyListeners(SWT.Selection, event);
							break;
						}
					}
				}
			});
			XtextSWTBotShell shell = bot.shell("Preferences");
			return new PreferencesDialogAPI(shell);
		} else {
			bot.menu("Window").menu("Preferences").click();
			return new PreferencesDialogAPI(bot.shell("Preferences"));
		}
```

**Comment by kthoms** [comment]
screenshot 23
Works on Photon

**Comment by cdietrich** [comment]
@kthoms could you have a look at the test on mac and my proposal?

**Comment by kthoms** [comment]
Works and looks identical on Oxygen target

**Comment by kthoms** [comment]
The test does not work on Mac, does not find the Preferences menu. Will now try with Christian's proposal.
Stacktrace:
```
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu item matching: with mnemonic 'Preferences'
	at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntilWidgetAppears(SWTBotFactory.java:472)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.menu(SWTBotMenu.java:272)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.menu(SWTBotMenu.java:255)
	at org.eclipse.swtbot.swt.finder.widgets.SWTBotMenu.menu(SWTBotMenu.java:217)
	at org.eclipse.xtend.ide.swtbot.api.MainMenuAPI.openPreferences(MainMenuAPI.java:27)
	at org.eclipse.xtend.ide.tests.preferences.FormatterPreferencesTest.formatterPreferencesEditDialog_CanBeOpenedAndAllSectionsExist(FormatterPreferencesTest.java:41)
	...
```

**Pull request merged**
