### PR TITLE
Xtext eclipse 813 automated ui tests

### PR DESCRIPTION
**Pull request by ArneDeutsch**

### CODE REVIEW

**Comment by cdietrich** [comment]
what is the intention behind this changes?

**Comment by ArneDeutsch** [comment]
There are some (very few) existing UI tests for Xtend. I have moved the infrastructore to a common subproject to avoid the redundance.

**Comment by cdietrich** [comment]
but why is stuff red then

**Comment by ArneDeutsch** [comment]
Damn. Multip-Repo-Issue. The shared project in moved to umbrella ... not availanble in Xtend ... argh ...

**Comment by ArneDeutsch** [comment]
Ok, made up my mind. Probably best to accept a bit of duplication here. Will keep the infrastructure as required by this test inside this project. Actually the duplication is not that big because the parts of the UI accessed by this test are other parts then from the test in umbrella. Will close this request.

**Pull request closed without merging**
