### PR TITLE
[381031] Add test case testUnusedFunction_1

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms karsten.thoms@itemis.de

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=381031

**Comment by meysholdt** [comment]
see [eclipse/xtext-extras#41#issuecomment-241000320](/eclipse/xtext-extras/pull/41#issuecomment-241000320)

**Comment by kthoms** [comment]
I think it does not harm to have this test here. Since there are also other tests in the same direction, I would tend to add this case here anyway, but add also test cases to xtext-extras.

**Comment by meysholdt** [comment]
agreed.

**Comment by kthoms** [comment]
Is it OK to merge?

**Comment by svenefftinge** [comment]
+1

**Pull request merged**
