### PR TITLE
[#149] allow extension fields in java 8 interfaces

### PR DESCRIPTION
**Pull request by cdietrich**
[#149] allow extension fields in java 8 interfaces

### CODE REVIEW

**Comment by szarnekow** [comment]
I assume the extensions are available in classes implementing the interface, too

**Review by szarnekow — APPROVED** [review]
Nice

**Comment by cdietrich** [comment]
> I assume the extensions are available in classes implementing the interface, too 
didnt test this. do we look up extensions in superclasses?

**Comment by szarnekow** [comment]
I think we consider inherited extensions. It should just work

**Comment by cdietrich** [comment]
it does not.  there is this done?

**Comment by szarnekow** [comment]
> it does not. there is this done?

Hmm for classes I see the equivalent example working fine:
```
class A {
	public static extension String s;
	def void m1(int i) {
		i.substring();
	}
}
class B extends A {
	def void m2(int i) {
		i.substring();
	}
}
```

**Comment by szarnekow** [comment]
And indeed it fails for interfaces:
```
interface A {
	@Extension
	public static String s;
	def void m1(int i) {
		i.substring();
	}
}
class B implements A {
	def void m2(int i) {
		i.substring(); // error
	}
}
```

**Comment by szarnekow** [comment]
`org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareReentrantTypeResolver.addExtensionFieldsToMemberSession(ResolvedTypes, IFeatureScopeSession, JvmDeclaredType, JvmIdentifiableElement, Set<String>, Set<JvmType>)` is only traversing the extended class with the wrong assumption that interfaces don't define fields.

**Comment by cdietrich** [comment]
replaced with https://github.com/eclipse/xtext/pull/2591

**Pull request closed without merging**
