### PR TITLE
avoid unused imports (tests)

### PR DESCRIPTION
**Pull request by nineninesevenfour**
fixes https://github.com/eclipse/xtext-xtend/issues/1029

Signed-off-by: Harald Fassler <harald.fassler+9974@gmail.com>

### CODE REVIEW

**Comment by cdietrich** [comment]
unfortunately upstream detection does not work automatically for gradle with PRs and not at all for maven
thus i pushed your branches manually and there are still test fails
https://ci.eclipse.org/xtext/job/xtext-xtend/job/nineninesevenfour-bugfix_issue1029/2/#showFailuresLink

to make this work with your two PRs you can use the repos built by your extras PR
https://ci.eclipse.org/xtext/job/xtext-extras/view/change-requests/job/PR-682/lastSuccessfulBuild/artifact/build/p2-repository/
https://ci.eclipse.org/xtext/job/xtext-extras/view/change-requests/job/PR-682/lastSuccessfulBuild/artifact/build/maven-repository/
and use them in relvant parts of the xtend build by temporary patching the files and push them with your PR and before merge reverting these changes

https://github.com/eclipse/xtext-xtend/blob/f4579f811eae58f8dfd86175dcbe02fcecaeb5b4/gradle/upstream-repositories.gradle#L32
https://github.com/eclipse/xtext-xtend/blob/f4579f811eae58f8dfd86175dcbe02fcecaeb5b4/releng/org.eclipse.xtend.target/org.eclipse.xtend.target-oxygen.target#L57

**Comment by nineninesevenfour** [comment]
Hello @cdietrich, thank you very much for testing this, I will have a look on it later.

**Comment by nineninesevenfour** [comment]
OK, finally running all green, thanks to your help! 🎉
But I have to clean up, before merging. 🧽

**Comment by cdietrich** [comment]
hmmm see fails in XtendCompilerMojoIT now. will check

**Comment by cdietrich** [comment]
https://github.com/cdietrich/xtend-nameclash-reproducer

**Pull request closed without merging**
