### PR TITLE
Compile sources from folders longrunning and smoke-suites

### PR DESCRIPTION
**Pull request by kthoms**
The folders
- longrunning/src
- longrunning/xtend-gen
- smoke-suites
were not configured as source folders properly. When imported as Gradle
project this requires that the dependencies on Equinox and PDE can be
resolved by Gradle.

Note: The new Buildship version seems to change the format of .classpath files. The file change was caused by a project re-import.

### CODE REVIEW

**Comment by cdietrich** [comment]
I thought all the time the previous strange config was intended by @spoenemann

**Comment by kthoms** [comment]
Maybe, but I am not aware of a reason.

**Comment by cdietrich** [comment]
Maybe cause the tests were executed by gradle as well before

**Comment by kthoms** [comment]
Hmm, maybe. But the Gradle build seems not to execute them, see http://services.typefox.io/open-source/jenkins/job/xtext-xtend/job/kth_core_tests_missing_sourcesets/

**Comment by spoenemann** [comment]
We should either make xtend.idea.tests independent of xtend.core.tests, which would allow to remove xtend.core.tests from the Gradle build so it's a pure PDE project, or extract the tests with PDE dependencies, e.g. move them to xtend.ui.tests.

**Comment by cdietrich** [comment]
@kthoms needs a rebase

**Comment by spoenemann** [comment]
Now that the Eclipse bundles are properly published on Maven Central, we should use the new group ids and versions, e.g. `org.eclipse.pde:org.eclipse.pde.core:3.11.1`

@kthoms could you update accordingly?

**Comment by spoenemann** [comment]
Sorry, I forgot that now with the Xtend compiler running in the Gradle build, the configuration of the additional source folders is more complex due to the different Xtend compiler outputs. I copied the configuration from xbase.tests. Now all source folders are included and the bundle is free of compile errors in my workspace.

**Pull request closed without merging**
