### PR TITLE
fixed extract method refactoring. 

### PR DESCRIPTION
**Pull request by cdietrich**
fixed extract method refactoring. 

resolves https://github.com/eclipse/xtext-extras/issues/107

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by kthoms** [comment]
This would fix the NPE, but the actual problem is that the return type is not computed correctly. Consider this file:
```
package test

import java.util.ArrayList
import org.eclipse.xtend.lib.annotations.Data

class Foo {
	Bar thisEnd
	def boolean test() {
		val int a = 5
		val x = '''«thisEnd.name»'''
		return new ArrayList<Integer>.addAll(#[a])
	}
}

@Data
class Bar {
	String name
}
```
If you extract the two lines `val x = ...` and `return ...`, then the refactoring would now determine void as the type. This will lead to a compile error, since the extracted method has a return statement with a type expectation, but it is incompatible with the declared return type void.

**Comment by cdietrich** [comment]
can we moved this discussion to the ticket. i hope @JanKoehnlein or @svenefftinge find the time to look at. since i dont know how to common supertype calculation is intended to work

**Comment by svenefftinge** [comment]
I will come up with a better fix

**Comment by svenefftinge** [comment]
See : https://github.com/eclipse/xtext-xtend/pull/190

**Pull request closed without merging**
