### PR TITLE
Activate useJenkinsSnapshots profile by default

### PR DESCRIPTION
**Pull request by kthoms**
Improves the experience with fresh checked out projects when dependent
snapshots are not available locally and must be downloaded.

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@kthoms no change for android archetype?

**Comment by kthoms** [comment]
have to check, thanks for the hint

**Comment by kthoms** [comment]
updated

**Comment by kthoms** [comment]
yes we should do this.

**Comment by kthoms** [comment]
the `org.eclipse.xtext.maven.parent` and `org.eclipse.xtext.maven.plugin` have this already set

**Pull request merged**
