### PR TITLE
[476555] Support for Annotations on Enum Literals in Xtend

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476555

**Comment by cdietrich** [comment]
please review

**Comment by kthoms** [comment]
Works as expected.

Before:
screenshot 69

After:
screenshot 70

**Comment by kthoms** [comment]
LGTM

**Pull request merged**
