### PR TITLE
[eclipse/xtext#1455] Fix line endings for JavaConverterTest.

### PR DESCRIPTION
**Pull request by ArneDeutsch**
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

### CODE REVIEW

**Comment by ArneDeutsch** [comment]
That's quite strange. Must be some subtle difference in line ending handling on our machines. If I do as you suggest the test fails for me. What if we call 'toUnixLineSeperator' in both places. Works then for me.

**Comment by miklossy** [comment]
Adding the `toUnixLineSeparator` to both places results in a failing test on my machine.
image

**Comment by cdietrich** [comment]
why is there windows endings in the expectation if you convert them?

**Comment by miklossy** [comment]
That is the point. Currently we convert only the line endings of the actual parameter (in 2 places), but we does not convert the line endings of the expected parameter. IMHO we should convert both of them to keep consistency.

**Pull request merged**
