### PR TITLE
(WIP) [xtext-xtend/1061] Provide ui test infrastructure for testing multi quickfixes [2/3]

### PR DESCRIPTION
**Pull request by drkstr101**
Task-Url: https://github.com/eclipse/xtext-xtend/issues/1061
Signed-off-by: Aaron R Miller <aaron.miller@waweb.io>

This PR implements `AbstractMultiQuickfixTest` in two new test classes, `EqualsWithNullMultiQuickfixTest` and `RemoveUnnecessaryModifiersMultiQuickfixTest`.

I have flagged the title as *WIP* to indicate that `RemoveUnnecessaryModifiersMultiQuickfixTest`still needs a little work. I should hopefully have this done firs tthing today, at which point I will post a follow up comment and remove the *WIP* flag in the title.

note: This PR also contains commits from https://github.com/eclipse/xtext-xtend/pull/1083

### CODE REVIEW

**Comment by drkstr101** [comment]
@miklossy 
Huh, I wonder what happened to my eclipsefdn/eca? It probably has something to do with me having to restore my workstation the other day. I thought it was just tied to the email address I use on git commit.

**Comment by miklossy** [comment]
> @miklossy
> Huh, I wonder what happened to my eclipsefdn/eca? It probably has something to do with me having to restore my workstation the other day. I thought it was just tied to the email address I use on git commit.

Hmm... I do not know. Maybe @cdietrich can give some hints about that.

**Comment by drkstr101** [comment]
Ohh, maybe it's because I didn't squash my commits? Shall I close and re-roll maybe?

**Comment by miklossy** [comment]
Could be. One single commit would be for sure better.

**Comment by drkstr101** [comment]
@miklossy Yeah it looks like one single commit was missing the signor info so it spoiled the whole batch. I had intended to squash anyways, so this is just a mistake on my part. I will get a good one up when I'm done for the day. Hopefully ready to merge.

**Comment by miklossy** [comment]
Ok.

**Pull request closed without merging**
