### PR TITLE
[440858] Add Override Proposals inside Inner Classes of Annotations

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=440858

**Comment by cdietrich** [comment]
please review

**Comment by kthoms** [comment]
Could you attach a screenshot of the effect?

**Comment by cdietrich** [comment]
bildschirmfoto 2017-02-24 um 15 28 22

**Pull request merged**
