### PR TITLE
replaced dependency to xbase.junit with xbase.testing

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@spoenemann can you have a look

**Comment by spoenemann** [comment]
Where do all the new classes in testdata come from?

**Comment by cdietrich** [comment]
copy & paste from xbase junit

**Comment by spoenemann** [comment]
Ok :+1:

**Comment by cdietrich** [comment]
unfortuantely we still are in the gradle vs manifest hell at runtime (e.g. of the tests)

**Pull request merged**
