### PR TITLE
[eclipse/xtext#1493] Fix broken launch configs for tests

### PR DESCRIPTION
**Pull request by drkstr101**
Task-Url: https://github.com/eclipse/xtext/issues/1493
Signed-off-by: Aaron R Miller <aaron.miller@waweb.io>

	note: partial/incomplete update

### CODE REVIEW

**Comment by szarnekow** [comment]
> partial/incomplete update

Does that mean I should wait with the review, or is this a partial change that is self contained?

**Comment by drkstr101** [comment]
It is a complete update for one specific broken launcher. It is incomplete in the sense that it does not address any others in this PR. (EG. issue should remain open after merge).

My apologies for the lack of clarity. I should have pasted [this comment](https://github.com/eclipse/xtext/issues/1493#issuecomment-653792683) into my commit notes.

**Comment by drkstr101** [comment]
FYI I am unaware of any other broken launchers, but would be happy to try and fix them if they were pointed out to me. I just happened to run this one and saw that it was broken.

**Comment by cdietrich** [comment]
ping @szarnekow

**Comment by cdietrich** [comment]
ping @szarnekow

**Comment by cdietrich** [comment]
thx @drkstr101

**Pull request merged**
