### PR TITLE
Use successful build from related branches

### PR DESCRIPTION
**Pull request by szarnekow**
Affected repos:
- xtext-core
- xtext-extras
- xtext-eclipse

### CODE REVIEW

**Comment by szarnekow** [comment]
It will run the Xtend content assist tests against the changed code in the other repos ...

**Comment by szarnekow** [comment]
I added you as a reviewer to make sure I did not miss one of the various pieces of code that need to be adjusted to make that work.

**Comment by cdietrich** [comment]
did you regenerate xtend @szarnekow

**Comment by szarnekow** [comment]
> did you regenerate xtend @szarnekow

Of course not. Adjusted and pushed.

**Pull request merged**
